[versions]
jvmTarget = "1.8"
ktlint = "0.45.2"

[libraries]
dependencyCheck = "org.owasp:dependency-check-gradle:7.4.4"
sonarQube = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.5.0.2730"
licenseReport = "com.github.jk1:gradle-license-report:2.1"
kotlinxDatetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"

databaseDrivers-postgres = "org.postgresql:postgresql:42.4.0"
databaseDrivers-mssql = "com.microsoft.sqlserver:mssql-jdbc:10.2.1.jre8"

test-junit = "org.junit.jupiter:junit-jupiter:5.9.2"

[plugins]
pluginPublish = "com.gradle.plugin-publish:1.0.0-rc-1"
spotless = "com.diffplug.spotless:6.12.0"
