[versions]
jvmTarget = "8"
ktlint = "0.48.2"

[libraries]
dependencyCheck = "org.owasp:dependency-check-gradle:8.1.0"
sonarQube = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.0.0.2929"
licenseReport = "com.github.jk1:gradle-license-report:2.1"
kotlinxDatetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"

databaseDrivers-postgres = "org.postgresql:postgresql:42.4.0"
databaseDrivers-mssql = "com.microsoft.sqlserver:mssql-jdbc:10.2.1.jre8"

test-junit = "org.junit.jupiter:junit-jupiter:5.9.2"

[plugins]
pluginPublish = "com.gradle.plugin-publish:1.1.0"
spotless = "com.diffplug.spotless:6.15.0"
